<a href="https://colab.research.google.com/github/nadiyasmin/skills-introduction-to-github/blob/main/PortfolioRefined.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sqlite3
import pandas as pd

In [3]:
conn = sqlite3.connect("mydb.db")
cursor = conn.cursor()

In [ ]:
cursor.execute('''
CREATE TABLE customers (
    customer_id VARCHAR(25) PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    email TEXT UNIQUE,
    phone VARCHAR(20) UNIQUE,
    address1 TEXT,
    address2 TEXT,
    city TEXT,
    state TEXT,
    postal_code INTEGER,
    country TEXT
)''')

In [7]:
cursor.executemany('''
INSERT INTO customers (customer_id, first_name, last_name, email, phone, address1, address2, city, state, postal_code, country)
VALUES (?,?,?,?,?,?,?,?,?,?,?)
''', [
    ('CUS202507300001', 'Nadia', 'Azis', 'nadiayasmin25@gmail.com', '60196195797', '12 Jalan Bunga Raya', 'Apartment B-12-3', 'Shah Alam', 'Selangor', 40150, 'Malaysia'),
    ('CUS202498310001', 'Jonathan', 'Byers', 'jonb@yahoo.com', '9023510783638', '742 Evergreen Terrace', 'Apt. 4B', 'Springfield', 'Illinois', 62704, 'United States'),
    ('CUS202498310002', 'Jake', 'Peralta', 'jakey999@gmail.com', '921838742132', '14 Oxford Street', 'Flat 3B', 'Highbury Court', 'London', 908000, 'United Kingdom'),
    ('CUS202507300002', 'Shin', 'Hari', 'lovemaybe@gmail.com', '62898947989', '7825 Maple Drive Suite 204', 'Crestview Plaza', 'Austin', 'Texas', 78731, 'United States'),
    ('CUS202507290001', 'Salman', 'Khan', 'salmankhann@hotmail.com', '+61893874737', 'No. 17 Lorong Teratai 2', 'Taman Mutiara Indah', 'Shah Alam', 'Selangor', 40150, 'Malaysia'),
    ('CUS202507290002', 'Siti', 'Fatimah', 'ctfatimah@gmail.com', '+0118377369', '23 Jalan Bukit Bintang', 'Apartment A-5-2 SkyView Residence', 'Kuala Lumpur', 'Kuala Lumpur', 55100, 'Malaysia')
])

conn.commit()

In [8]:
cursor.execute('''
CREATE TABLE category (
    category_id VARCHAR(40) PRIMARY KEY,
    category_name TEXT
)''')

In [9]:
cursor.executemany('''
INSERT INTO category (category_id, category_name)
VALUES (?,?)
''', [
      ('CAT0001', 'Fashion'),
      ('CAT0002', 'Furniture'),
      ('CAT0003', 'Toys and hobbies'),
      ('CAT0004', 'Beverages'),
      ('CAT0005', 'Household'),
      ('CAT0006', 'Auto and parts'),
      ('CAT0007', 'Accessories'),
      ('CAT0008', 'Appliances'),
      ('CAT0009', 'Books'),
      ('CAT0010', 'Health'),
      ('CAT0011', 'Electronics'),
      ('CAT0012', 'Beauty'),
      ('CAT0013', 'Food'),
      ('CAT0014', 'Beverages')
])
conn.commit()

In [10]:
cursor.execute('''
CREATE TABLE products (
    product_id VARCHAR(40) PRIMARY KEY,
    product_name TEXT,
    price DECIMAL(10,2),
    stock_quantity INTEGER,
    category_id VARCHAR(40),
    FOREIGN KEY (category_id) REFERENCES category(category_id)
)''')

In [11]:
cursor.executemany('''
INSERT INTO products (product_id, product_name, price, stock_quantity, category_id)
VALUES (?,?,?,?,?)
''', [
      ('PRD0001', 'Leather Handbag', 89.99, 50, 'CAT0001'),
      ('PRD0002', 'Wooden Coffee Table', 149, 20, 'CAT0002'),
      ('PRD0003', 'RC Drone', 129.95, 35, 'CAT0003'),
      ('PRD0004', 'Organic Green Tea (box)', 6.25, 100, 'CAT0014'),
      ('PRD0005', 'Vacuum Cleaner', 159.99, 18, 'CAT0008'),
      ('PRD0006', 'Car Air Filter', 24.75, 60, 'CAT0006'),
      ('PRD0007', 'Gold-Plated Necklace', 45, 80, 'CAT0007'),
      ('PRD0008', 'Smart LED Bulb', 14.99, 150, 'CAT0005'),
      ('PRD0009', 'Yoga Mat', 29.5, 70, 'CAT0010'),
      ('PRD0010', 'Facial Moisturizer', 19.9, 90, 'CAT0012'),
      ('PRD0011', 'Bluetooth Speaker', 59.99, 45, 'CAT0011'),
      ('PRD0012', 'Men’s Sneakers', 74.95, 55, 'CAT0001'),
      ('PRD0013', 'Hardcover Novel', 12.99, 120, 'CAT0009'),
      ('PRD0014', 'Kids Building Blocks Set', 34.99, 40, 'CAT0003'),
      ('PRD0015', 'Instant Coffee Pack', 9.45, 95, 'CAT0004'),
      ('PRD0016', 'Double-Door Refrigerator', 899, 10, 'CAT0008'),
      ('PRD0017', 'Protein Snack Bar (Box of 6)', 11.25, 65, 'CAT0013'),
      ('PRD0018', 'Essential Oil Diffuser', 36.75, 75, 'CAT0005'),
      ('PRD0019', 'Windshield Wipers (Set)', 22.1, 30, 'CAT0006'),
      ('PRD0020', 'Wireless Earbuds', 79, 55, 'CAT0011')
])
conn.commit()

In [12]:
cursor.execute('''
CREATE TABLE payments (
    payment_id VARCHAR(30) PRIMARY KEY,
    order_id VARCHAR(40),
    payment_method TEXT,
    payment_date DATE,
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
)''')

In [13]:
cursor.executemany('''
INSERT INTO payments (payment_id, order_id, payment_method, payment_date)
VALUES (?,?,?,?)
''', [
      ('PYM0001', 'ORD0001', 'Debit/Credit Card', '2024-04-24'),
      ('PYM0002', 'ORD0002', 'PayPal', '2025-01-01'),
      ('PYM0003', 'ORD0003', 'Atome', '2024-0925'),
      ('PYM0004', 'ORD0004', 'Atome', '2025-06-27'),
      ('PYM0005', 'ORD0005', 'Debit/Credit Card', '2024-04-18'),
      ('PYM0006', 'ORD0006', 'Debit/Credit Card', '2024-07-25'),
      ('PYM0007', 'ORD0007', 'Debit/Credit Card', '2024-09-15'),
      ('PYM0008', 'ORD0008', 'Online Banking', '2024-01-01')

])
conn.commit()

In [ ]:
cursor.execute('''
DROP TABLE orders''')

In [14]:
cursor.execute('''
CREATE TABLE orders (
    order_id VARCHAR(40) PRIMARY KEY,
    customer_id VARCHAR(25),
    order_date DATE,
    ship_date DATE,
    delivery_date DATE,
    status TEXT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
)''')

In [ ]:
cursor.executemany('''
INSERT INTO orders (order_id, customer_id, order_date, ship_date, delivery_date, status)
VALUES (?,?,?,?,?,?)
''', [
      ('ORD0001', 'CUS202507300001', '2024-04-24', '2024-04-25', '2024-04-26', 'DELIVERED'),
      ('ORD0002', 'CUS202498310001', '2025-01-01', '2025-01-02', '2025-01-03', 'DELIVERED'),
      ('ORD0003', 'CUS202498310002', '2024-09-25', '2024-09-26', '2024-09-27', 'REFUNDED'),
      ('ORD0004', 'CUS202507300002', '2025-06-27', None, None, 'TO BE SHIPPED'),
      ('ORD0005', 'CUS202507290001', '2024-04-18', None, None, 'REFUNDED'),
      ('ORD0006', 'CUS202507290002', '2024-07-25', '2024-07-26', None, 'SHIPPED'),
      ('ORD0007', 'CUS202498310001', '2024-09-15', '2024-09-16', None, 'SHIPPED'),
      ('ORD0008', 'CUS202507290002', '2024-01-01', '2024-01-02', '2024-01-03', 'DELIVERED')

])
conn.commit()

In [18]:
cursor.execute('''
CREATE TABLE orders_items (
    order_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id VARCHAR(40),
    product_id VARCHAR(40),
    quantity INTEGER,
    price DECIMAL(10,2),
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
)''')

In [22]:
cursor.executemany('''
INSERT INTO orders_items (order_id, product_id, quantity, price)
VALUES (?,?,?,?)
''', [
      ('ORD0001', 'PRD0012', 1, 74.95),
      ('ORD0001', 'PRD0001', 1, 89.99),
      ('ORD0001', 'PRD0007', 1, 45),
      ('ORD0002', 'PRD0018', 2, 36.75),
      ('ORD0002', 'PRD0015', 3, 9.45),
      ('ORD0003', 'PRD0017', 1, 11.25),
      ('ORD0004', 'PRD0018', 6, 36.75),
      ('ORD0005', 'PRD0019', 1, 22.1),
      ('ORD0006', 'PRD0020', 7, 79),
      ('ORD0007', 'PRD0003', 10, 129.95),
      ('ORD0008', 'PRD0004', 5, 6.25)

])
conn.commit()

In [24]:
query = """
SELECT * FROM orders_items
"""
df = pd.read_sql_query(query, conn)
df

    order_item_id order_id product_id  quantity   price
0               1  ORD0001    PRD0012         1   74.95
1               2  ORD0001    PRD0001         1   89.99
2               3  ORD0001    PRD0007         1   45.00
3               4  ORD0002    PRD0018         2   36.75
4               5  ORD0002    PRD0015         3    9.45
5               6  ORD0003    PRD0017         1   11.25
6               7  ORD0004    PRD0018         6   36.75
7               8  ORD0005    PRD0019         1   22.10
8               9  ORD0006    PRD0020         7   79.00
9              10  ORD0007    PRD0003        10  129.95
10             11  ORD0008    PRD0004         5    6.25

In [ ]:
query = """
SELECT
        o.order_id,
        o.customer_id,
        o.product_id,
        o.quantity,
        o.order_date,
        o.ship_date,
        o.delivery_date,
        o.status,
        p.payment_method
FROM orders o
LEFT JOIN payments p ON o.order_id = p.order_id
"""
df = pd.read_sql_query(query, conn)
df

In [ ]:
query = """
SELECT
    c.category_name,
    SUM(o.quantity*p.price) AS total_sales
    FROM orders o
    JOIN products p ON o.product_id = p.product_id
    JOIN category c ON p.category_id = c.category_id
    GROUP BY c.category_name
    ORDER BY total_sales DESC
"""
df = pd.read_sql_query(query, conn)
df

In [ ]:
query = """
SELECT
    p.product_name,
    SUM(o.quantity) AS total_quantity_ordered
    FROM orders o
    JOIN products p ON o.product_id = p.product_id
    GROUP BY p.product_name
    ORDER BY total_quantity_ordered DESC
    LIMIT 1
"""
df = pd.read_sql_query(query, conn)
df

     product_name  total_quantity_ordered
0  Men’s Sneakers                       4

In [ ]:
query = """
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    o.order_id,
    o.order_date,
    p.product_name,
    o.quantity,
    p.price,
    (o.quantity * p.price) AS total_amount
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN products p ON o.product_id = p.product_id
    ORDER BY c.customer_id, o.order_date;
"""
df = pd.read_sql_query(query, conn)
df

,customer_name,order_id,order_date,product_name,quantity,price,total_amount
0,Jonathan Byers,ORD0007,2024-09-15,Bluetooth Speaker,2,59.99,119.98
1,Jonathan Byers,ORD0002,2025-01-01,Wireless Earbuds,1,79.00,79.00
2,Jake Peralta,ORD0003,2024-09-25,Organic Green Tea (box),3,6.25,18.75
3,Salman Khan,ORD0005,2024-04-18,Gold-Plated Necklace,1,45.00,45.00
4,Siti Fatimah,ORD0008,2024-01-01,Men’s Sneakers,2,74.95,149.90
5,Siti Fatimah,ORD0006,2024-07-25,Hardcover Novel,1,12.99,12.99
6,Nadia Azis,ORD0001,2024-04-24,Men’s Sneakers,2,74.95,149.90
7,Shin Hari,ORD0004,2025-06-27,Leather Handbag,1,89.99,89.99